### ISSUE TITLE
Can `PrepareRelease` and `Release` be in different workflows?

### ISSUE THREAD

**Issue by BatmanAoD** [knope-dev/knope#1267]
You've previously mentioned that you wanted to be able to split the preparation workflow from the release workflow, so that they could be run as two separate steps. I thought that work was already done, but now I can't find where you referred to it.

It appears that this _mostly_ works, but git tags are not created. Is that the expected behavior for now?

**Comment by dbanty** [comment]
It definitely _should_ work, but I think I've mostly used it with GitHub releases [like this example](https://knope.tech/recipes/1-preview-releases-with-pull-requests/) so maybe there's something broken with tags 🤔

**Comment by BatmanAoD** [comment]
Putting the workflow back in one step worked. Just in case this is due to me screwing something up, here's the non-working Knope.toml:

<details>

```toml
[package]
versioned_files = ["python-grpc/pyproject.toml", "python-grpc-betterproto/pyproject.toml", "rust/Cargo.toml", "golang/go.mod"]

[[workflows]]
name = "prepare"

[[workflows.steps]]
type = "PrepareRelease"
allow_empty = true

[[workflows.steps]]
type = "Command"
# Knope feature request to make this behavior automatic:
# https://github.com/knope-dev/knope/issues/162
command = "cargo update -w --manifest-path rust/Cargo.toml"

[[workflows]]
name = "release"

# Needed so that `prepare` and `release` can run in separate CI steps
[[workflows.steps]]
type = "Command"
command = "git add python-grpc/pyproject.toml python-grpc-betterproto/pyproject.toml rust/Cargo.toml rust/Cargo.lock golang/go.mod"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[workflows.steps.variables]
# `Version` is a "magic" Knope string that will be replaced with the actual version
"$version" = "Version"

[[workflows.steps]]
type = "Release"

# Needed because Knope doesn't have built-in GitLab support
[[workflows.steps]]
type = "Command"
command = "git push --push-option ci.skip"

[[workflows.steps]]
type = "Command"
command = "git push --tags --push-option ci.skip"

[[workflows.steps]]
type = "Command"
# See https://docs.gitlab.com/ee/user/project/releases/release_cli.html
command = "release-cli create --name \"Release $version\" --tag-name \"v$version\" --ref \"v$version\""

[workflows.steps.variables]
"$version" = "Version"
```

</details>

And the working one:

<details>

```toml
[package]
versioned_files = ["python-grpc/pyproject.toml", "python-grpc-betterproto/pyproject.toml", "rust/Cargo.toml", "golang/go.mod"]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"
allow_empty = true

[[workflows.steps]]
type = "Command"
# Knope feature request to make this behavior automatic:
# https://github.com/knope-dev/knope/issues/162
command = "cargo update -w --manifest-path rust/Cargo.toml"

# Needed so that `prepare` and `release` can run in separate CI steps
[[workflows.steps]]
type = "Command"
command = "git add python-grpc/pyproject.toml python-grpc-betterproto/pyproject.toml rust/Cargo.toml rust/Cargo.lock golang/go.mod"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[workflows.steps.variables]
# `Version` is a "magic" Knope string that will be replaced with the actual version
"$version" = "Version"

[[workflows.steps]]
type = "Release"

# Needed because Knope doesn't have built-in GitLab support
[[workflows.steps]]
type = "Command"
command = "git push --push-option ci.skip"

[[workflows.steps]]
type = "Command"
command = "git push --tags --push-option ci.skip"

[[workflows.steps]]
type = "Command"
# See https://docs.gitlab.com/ee/user/project/releases/release_cli.html
command = "release-cli create --name \"Release $version\" --tag-name \"v$version\" --ref \"v$version\""

[workflows.steps.variables]
"$version" = "Version"
```

</details>

The diff is merely:

```
--- a/knope.toml
+++ b/knope.toml
@@ -2,7 +2,7 @@
 versioned_files = ["python-grpc/pyproject.toml", "python-grpc-betterproto/pyproject.toml", "rust/Cargo.toml", "golang/go.mod"]

 [[workflows]]
-name = "prepare"
+name = "release"

 [[workflows.steps]]
 type = "PrepareRelease"
@@ -14,9 +14,6 @@
 # https://github.com/knope-dev/knope/issues/162
 command = "cargo update -w --manifest-path rust/Cargo.toml"

-[[workflows]]
-name = "release"
-
 # Needed so that `prepare` and `release` can run in separate CI steps
 [[workflows.steps]]
 type = "Command"
```
