### ISSUE TITLE
Allow specifying multiple, independent packages.

### ISSUE THREAD

**Issue by dbanty** [knope-dev/knope#153]
Change the way that single-package definition works so it looks like this:

```toml
[package]
versioned_files = [...]
changelog = ""
```

For _multiple_ packages, it should look like this:

```toml
[[packages]]
versioned_files = [...]
changelog = ""
name = ""  # New required field when defining multiple
```

The `name` field will be usable in a few ways:

1. When creating a GitHub release, name it "<Name> <Version>" to differentiate between releases (with notes) for different packages.
2. The tag of the release should be `<name>/v<version>` to avoid version tag conflicts. This is the tagging scheme supported by Go modules—as long as name is the same as directory.
3. Useful to include in logging to specify which packages are being updated, especially in dry-runs

The `BumpVersion` and `Release` steps will apply to all packages.
