### ISSUE TITLE
Segfault when creating a tag in `Release` step for macOS x86 prebuilt binaries

### ISSUE THREAD

**Issue by dbanty** [knope-dev/knope#231]
So far this only happens when using a prebuilt binary on x86 macOS (e.g., using `cargo-binstall` to install)—but the `Release` step—if it creates a Git tag—segfaults 😭.

The easiest thing might be to replace usage with the new Rust-based crate (part of #229) rather than trying to track down the C-located error 😬.

## Sample knope.toml

```toml
[[packages]]
versioned_files = []

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit  --allow-empty -m \"chore: prepare release $version\""
variables = { "$version" = "Version" }

[[workflows.steps]]
type = "Release"
```

## Sample Output

```
% knope release
[main 4febb70] chore: prepare release 0.2.1
[1]    40019 segmentation fault  knope release
```
