### ISSUE TITLE
Allow multi-package repos to have shared packages that will trigger version bumps in its dependents.

### ISSUE THREAD

**Issue by MarquessV** [knope-dev/knope#306]
Consider a repo with three packages:

```toml
[packages.common]
versioned_files = ["common/Cargo.toml"]
changelog = "common/CHANGELOG.md"
scopes = ["common"]

[packages.package-that-uses-common]
versioned_files = ["package-that-uses-common/Cargo.toml"]
changelog = "package-that-uses-common/CHANGELOG.md"
scopes = ["package_that_uses_common"]

[packages.another-package-that-uses-common]
versioned_files = ["another-package-that-uses-common/Cargo.toml"]
changelog = "another-package-that-uses-common/CHANGELOG.md"
scopes = ["another_package_that_uses_common"]
```
In this case, it's possible to update `package-that-uses-common` and `another-package-that-uses-common` independently from the other packages, so they should be versioned separately. 

However, updates to `common` should always update both other packages. Therefore, anytime `common` needs to be version bumped, so should both of the sub-packages.

Currently, if we were to publish a commit like `fix(common): ...` then `knope` would bump `common` without bumping the dependent packages (both the `common` dependency and the version of each dependent). This makes it impossible to build and release the other packages without manual intervention or a complex workflow. One could add the `common` scope to each sub-package, but then changes to common are duplicated across each changelog.

There are other intricacies with this:

1. How should `knope` recognize these dependencies?
2. What if `common` gets a breaking change? Should `knope` just assume it'll work with the dependent packages and bump it anyways?
3. This probably isn't _always_ the desired use case, so how should users be allowed to opt in or out?
