### ISSUE TITLE
Update version in more places

### ISSUE THREAD

**Issue by dbanty** [knope-dev/knope#482]
There are many times you'll want to keep your version up to date in multiple places (e.g., documentation's install instructions). Knope should facilitate this somehow. The most obvious solution is probably regex match groups for set files but maybe there's a simpler option (that doesn't require testing regexs, which is hard)?

**Comment by alex-way** [comment]
Just throwing out a potentially terrible idea here but could something like the following work:

```toml
[package]
# Query parameter style. Similar to vite asset importing: https://vitejs.dev/guide/assets.html#importing-asset-as-string
versioned_files = ["docker-compose.yml?replace=REGEX$version"]
```

```toml
[package]
# Potentially simpler, but could be limiting if further features are required in the future
versioned_files = ["docker-compose.yml:REGEX$version"]
```

The idea being that there's a defined separator (`?` or `:`) between the filename (`docker-compose.yml`) and the regex. One other thing we'll need is an identifier for the current version rather than relying on regex. I suggest `$version` as it's what's used elsewhere in the documentation for similar purposes.

We'd need to replace the $version first, prior to evaluating the regex to avoid the `$version` from mangling the regex.

I think whatever method is implemented should only be used as a fallback and as further development is done to parse different files, the reliance on this should be less prevalent and hopefully less of an issue.
