### ISSUE TITLE
Command to print the current package version(s)

### ISSUE THREAD

**Issue by BatmanAoD** [knope-dev/knope#988]
Since determining the version of a package is nontrivial, and it's often useful in scripts (e.g. in CI), I think it would be a great feature if Knope could detect the current version(s) of packages and print that, without doing anything else.

Users could probably parse this information out of `knope release --dry-run`, but that's a bit awkward.

The primary use case I'm thinking of is to replace stuff like `git describe --abbrev=0 --tags | sed 's/v//'`, so the output must be easy to parse. For a standard, single package, it could just print the version it finds; for multiple packages, it could print `<name>=<version>`, one on each line. Just like `release`, when a package has multiple versioned files and their versions don't match, it should just print an error of some kind.

**Comment by dbanty** [comment]
For single packages, this would work today:

```toml
[[workflows]]
name = "print-version"

[[workflows.steps]]
type = "Command"
command = "echo $version"
variables = { "$version" = "Version" }
```

For multi-package setups, we'd have to decide on something new. We really need a way to use variables with multiple packages _anyway_ 😅.

**Comment by dbanty** [comment]
(I guess my suggestion is exactly what you had in #885)

**Comment by BatmanAoD** [comment]
I completely forgot I had asked for that, and didn't see it in the issues list when I searched 😅

**Comment by dbanty** [comment]
Converting this issue to specifically figure out outputting versions for multiple packages (since #885 / #994 will cover the single-package case)

**Comment by BatmanAoD** [comment]
I've updated the issue title & description accordingly.

**Comment by BatmanAoD** [comment]
I can think of three possible approaches here:

* "namespace" the `ChangelogEntry` and `Version` variables:
  ```toml
  [[workflows.steps]]
  type = "Command"
  command = "echo \"$version\""

  [workflows.steps.variables]
  "$version" = "packagename.Version"
  ```
* Let workflows specify steps that only apply to specific packages; each step is performed separately for each package in the list:
  ```toml
  [[workflows.steps]]
  type = "Command"
  packages: ["packagename"]
  command = "echo \"$version\""

  [workflows.steps.variables]
  "$version" = "Version"
  ```
* Enable defining workflows that are specific to a package:
  ```toml
  [packages.packagename]
  versioned_files = ["crates/packagename/Cargo.toml", "Cargo.lock"]
  scopes = ["packagename"]

  [[packages.packagename.workflows]]
  ```

I think the second option, workflow steps that run separately in each package from an explicit list, looks like it has the right balance of flexibility without requiring too much code-duplication in common cases, and I would expect it to be not terribly difficult to implement.

...I also have a few half-baked alternatives that might be worth mentioning in case they spark an idea:

* Introduce a new top-level value, something like `[[single_package_workflows]]`, that defines workflows that run on a specific package, ignoring other packages.
* Introduce "workspaces". Having a `knope.toml` within a specific crate, instead of at the workspace root, appears to work already, so maybe Knope could also have a way to "mix" single-package and multi-package modes by having a multi-package config at the root level and single-package configs in each package.

**Comment by smcnamee-naii** [comment]
Just ran into this limitation. I'm noticing that some workflow steps always run once per workflow (e.g., [Release](https://knope.tech/reference/config-file/steps/release/) and [Command](https://knope.tech/reference/config-file/steps/command/)) while others support running once per package (e.g., [BumpVersion](https://knope.tech/reference/config-file/steps/bump-version/) and [PrepareRelease](https://knope.tech/reference/config-file/steps/prepare-release/)) and automatically do so when multiple packages are configured.

The issue here seems that there's no established "opt in" pattern for the jump to per-package execution, especially when one may want to control which packages do/don't run. While @BatmanAoD's `packages: ["packagename"]` seems flexible, I believe configuring 'for all packages' should be less verbose.

Taking inspiration from the `[[single_package_workflows]]` suggestion, why not something like:

```toml
# Single Package Workflow - No change

[[workflows]]
name = "print-version"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "echo $version"
variables = { "$version" = "Version" }
```

```toml
# Multiple Package Workflow - steps with `multiple` make it clear 
# which steps apply at a 'package scope' (and may run multiple times)

[[workflows]]
name = "print-version"

[[workflows.multiple.steps]]
type = "PrepareRelease"
# `multi` steps by default apply to all packages

[[workflows.multiple.steps]]
type = "Command"
command = "echo $version"
variables = { "$version" = "Version" }
# Limit to specific packages with `packages_include`
packages_include = ["packagename1", "packagename2"]

[[workflows.multiple.steps]]
type = "Command"
command = "echo $version"
variables = { "$version" = "Version" }
# Exclude specific packages with `packages_exclude`
packages_exclude = ["packagename3"]

[[workflows.steps]]
type = "Command"
command = "echo 'this step only runs once!'"
```

The change of also adding `multiple` to `PrepareRelease` might be a hard sell, but I'm trying to push for consistency and readability. New developers shouldn't need to go to the docs to understand how many times a step will run, especially if they have the control to make something `multiple`.
